version: '3'
services:
  booking:
    build:
      context: .
      dockerfile: booking/Dockerfile

    environment:
      - password=0000
      - login=postgres
    ports:
      - "8080:8080"
      - "5433:5433"